export { default as Person } from '@/assets/Images/Png/Person.png'
export { default as Rating_1 } from '@/assets/Images/Png/Rating_1.png'
export { default as Rating_2 } from '@/assets/Images/Png/Rating_2.png'
export { default as Rating_3 } from '@/assets/Images/Png/Rating_3.png'
export { default as Auth_Photo } from '@/assets/Images/Png/Auth_Photo.png'
export { default as Partner_American } from '@/assets/Images/Png/Partner_American.png'
export { default as Partner_Klarna } from '@/assets/Images/Png/Partner_Klarna.png'
export { default as Partner_Skrill } from '@/assets/Images/Png/Partner_Skrill.png'
export { default as Partner_West } from '@/assets/Images/Png/Partner_West.png'
export { default as Footer_Logo } from '@/assets/Images/Png/Footer_Logo.png'
export { default as Cource1 } from '@/assets/Images/Png/Cource1.png'
export { default as Cource2 } from '@/assets/Images/Png/Cource2.png'
export { default as Cource3 } from '@/assets/Images/Png/Cource2.png'
export { default as Service } from './Service.png'
export { default as Ava_1 } from './Ava_1.png'
export { default as Ava_2 } from './Ava_2.png'
export { default as Expert } from './Expert.png'
export {default as User_Icon} from './user_icon.png'
export {default as Hero_Banner} from './hero_banner.png'
export {default as QuoteBannerImg} from './quoteBanner.png'
export {default as Quote_Icon} from './Quote.png'
export {default as Amazon} from './Amazon.webp'
export {default as Poster_1} from './Poster_1.jpg'
export {default as Poster_2} from './Poster_2.jpg'
export {default as Poster_3} from './Poster_3.jpg'
export {default as Contact_Banner} from './contact_banner.png'