/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as apphomeRouteRouteImport } from './routes/(app)/(home)/route'
import { Route as appContactRouteRouteImport } from './routes/(app)/contact/route'
import { Route as appFinanceRouteRouteImport } from './routes/(app)/finance/route'
import { Route as appProfileRouteRouteImport } from './routes/(app)/profile/route'
import { Route as appProgramsRouteRouteImport } from './routes/(app)/programs/route'
import { Route as authsigninRouteRouteImport } from './routes/(auth)/(signin)/route'
import { Route as authsignupRouteRouteImport } from './routes/(auth)/(signup)/route'
import { Route as apphomeIndexRouteImport } from './routes/(app)/(home)/index'
import { Route as appContactIndexRouteImport } from './routes/(app)/contact/index'
import { Route as appFinanceIndexRouteImport } from './routes/(app)/finance/index'
import { Route as appProfileIndexRouteImport } from './routes/(app)/profile/index'
import { Route as appProgramsIndexRouteImport } from './routes/(app)/programs/index'
import { Route as appProgramsCourseIdRouteImport } from './routes/(app)/programs/$courseId'
import { Route as authsigninSigninRouteImport } from './routes/(auth)/(signin)/signin'
import { Route as authsignupSignupRouteImport } from './routes/(auth)/(signup)/signup'

const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const apphomeRouteRoute = apphomeRouteRouteImport.update({
  id: '/(home)',
  getParentRoute: () => appRouteRoute,
} as any)
const appContactRouteRoute = appContactRouteRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => appRouteRoute,
} as any)
const appFinanceRouteRoute = appFinanceRouteRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => appRouteRoute,
} as any)
const appProfileRouteRoute = appProfileRouteRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => appRouteRoute,
} as any)
const appProgramsRouteRoute = appProgramsRouteRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => appRouteRoute,
} as any)
const authsigninRouteRoute = authsigninRouteRouteImport.update({
  id: '/(signin)',
  getParentRoute: () => authRouteRoute,
} as any)
const authsignupRouteRoute = authsignupRouteRouteImport.update({
  id: '/(signup)',
  getParentRoute: () => authRouteRoute,
} as any)
const apphomeIndexRoute = apphomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => apphomeRouteRoute,
} as any)
const appContactIndexRoute = appContactIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appContactRouteRoute,
} as any)
const appFinanceIndexRoute = appFinanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appFinanceRouteRoute,
} as any)
const appProfileIndexRoute = appProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appProfileRouteRoute,
} as any)
const appProgramsIndexRoute = appProgramsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appProgramsRouteRoute,
} as any)
const appProgramsCourseIdRoute = appProgramsCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => appProgramsRouteRoute,
} as any)
const authsigninSigninRoute = authsigninSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => authsigninRouteRoute,
} as any)
const authsignupSignupRoute = authsignupSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authsignupRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/contact': typeof appContactRouteRouteWithChildren
  '/finance': typeof appFinanceRouteRouteWithChildren
  '/profile': typeof appProfileRouteRouteWithChildren
  '/programs': typeof appProgramsRouteRouteWithChildren
  '/programs/$courseId': typeof appProgramsCourseIdRoute
  '/signin': typeof authsigninSigninRoute
  '/signup': typeof authsignupSignupRoute
  '/': typeof apphomeIndexRoute
  '/contact/': typeof appContactIndexRoute
  '/finance/': typeof appFinanceIndexRoute
  '/profile/': typeof appProfileIndexRoute
  '/programs/': typeof appProgramsIndexRoute
}
export interface FileRoutesByTo {
  '/programs/$courseId': typeof appProgramsCourseIdRoute
  '/signin': typeof authsigninSigninRoute
  '/signup': typeof authsignupSignupRoute
  '/': typeof apphomeIndexRoute
  '/contact': typeof appContactIndexRoute
  '/finance': typeof appFinanceIndexRoute
  '/profile': typeof appProfileIndexRoute
  '/programs': typeof appProgramsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/(auth)': typeof authRouteRouteWithChildren
  '/(app)/(home)': typeof apphomeRouteRouteWithChildren
  '/(app)/contact': typeof appContactRouteRouteWithChildren
  '/(app)/finance': typeof appFinanceRouteRouteWithChildren
  '/(app)/profile': typeof appProfileRouteRouteWithChildren
  '/(app)/programs': typeof appProgramsRouteRouteWithChildren
  '/(auth)/(signin)': typeof authsigninRouteRouteWithChildren
  '/(auth)/(signup)': typeof authsignupRouteRouteWithChildren
  '/(app)/programs/$courseId': typeof appProgramsCourseIdRoute
  '/(auth)/(signin)/signin': typeof authsigninSigninRoute
  '/(auth)/(signup)/signup': typeof authsignupSignupRoute
  '/(app)/(home)/': typeof apphomeIndexRoute
  '/(app)/contact/': typeof appContactIndexRoute
  '/(app)/finance/': typeof appFinanceIndexRoute
  '/(app)/profile/': typeof appProfileIndexRoute
  '/(app)/programs/': typeof appProgramsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/contact'
    | '/finance'
    | '/profile'
    | '/programs'
    | '/programs/$courseId'
    | '/signin'
    | '/signup'
    | '/'
    | '/contact/'
    | '/finance/'
    | '/profile/'
    | '/programs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/programs/$courseId'
    | '/signin'
    | '/signup'
    | '/'
    | '/contact'
    | '/finance'
    | '/profile'
    | '/programs'
  id:
    | '__root__'
    | '/(app)'
    | '/(auth)'
    | '/(app)/(home)'
    | '/(app)/contact'
    | '/(app)/finance'
    | '/(app)/profile'
    | '/(app)/programs'
    | '/(auth)/(signin)'
    | '/(auth)/(signup)'
    | '/(app)/programs/$courseId'
    | '/(auth)/(signin)/signin'
    | '/(auth)/(signup)/signup'
    | '/(app)/(home)/'
    | '/(app)/contact/'
    | '/(app)/finance/'
    | '/(app)/profile/'
    | '/(app)/programs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  authRouteRoute: typeof authRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(home)': {
      id: '/(app)/(home)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof apphomeRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/contact': {
      id: '/(app)/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof appContactRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/finance': {
      id: '/(app)/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof appFinanceRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/profile': {
      id: '/(app)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof appProfileRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/programs': {
      id: '/(app)/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof appProgramsRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(auth)/(signin)': {
      id: '/(auth)/(signin)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authsigninRouteRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/(signup)': {
      id: '/(auth)/(signup)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authsignupRouteRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(app)/(home)/': {
      id: '/(app)/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof apphomeIndexRouteImport
      parentRoute: typeof apphomeRouteRoute
    }
    '/(app)/contact/': {
      id: '/(app)/contact/'
      path: '/'
      fullPath: '/contact/'
      preLoaderRoute: typeof appContactIndexRouteImport
      parentRoute: typeof appContactRouteRoute
    }
    '/(app)/finance/': {
      id: '/(app)/finance/'
      path: '/'
      fullPath: '/finance/'
      preLoaderRoute: typeof appFinanceIndexRouteImport
      parentRoute: typeof appFinanceRouteRoute
    }
    '/(app)/profile/': {
      id: '/(app)/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof appProfileIndexRouteImport
      parentRoute: typeof appProfileRouteRoute
    }
    '/(app)/programs/': {
      id: '/(app)/programs/'
      path: '/'
      fullPath: '/programs/'
      preLoaderRoute: typeof appProgramsIndexRouteImport
      parentRoute: typeof appProgramsRouteRoute
    }
    '/(app)/programs/$courseId': {
      id: '/(app)/programs/$courseId'
      path: '/$courseId'
      fullPath: '/programs/$courseId'
      preLoaderRoute: typeof appProgramsCourseIdRouteImport
      parentRoute: typeof appProgramsRouteRoute
    }
    '/(auth)/(signin)/signin': {
      id: '/(auth)/(signin)/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof authsigninSigninRouteImport
      parentRoute: typeof authsigninRouteRoute
    }
    '/(auth)/(signup)/signup': {
      id: '/(auth)/(signup)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authsignupSignupRouteImport
      parentRoute: typeof authsignupRouteRoute
    }
  }
}

interface apphomeRouteRouteChildren {
  apphomeIndexRoute: typeof apphomeIndexRoute
}

const apphomeRouteRouteChildren: apphomeRouteRouteChildren = {
  apphomeIndexRoute: apphomeIndexRoute,
}

const apphomeRouteRouteWithChildren = apphomeRouteRoute._addFileChildren(
  apphomeRouteRouteChildren,
)

interface appContactRouteRouteChildren {
  appContactIndexRoute: typeof appContactIndexRoute
}

const appContactRouteRouteChildren: appContactRouteRouteChildren = {
  appContactIndexRoute: appContactIndexRoute,
}

const appContactRouteRouteWithChildren = appContactRouteRoute._addFileChildren(
  appContactRouteRouteChildren,
)

interface appFinanceRouteRouteChildren {
  appFinanceIndexRoute: typeof appFinanceIndexRoute
}

const appFinanceRouteRouteChildren: appFinanceRouteRouteChildren = {
  appFinanceIndexRoute: appFinanceIndexRoute,
}

const appFinanceRouteRouteWithChildren = appFinanceRouteRoute._addFileChildren(
  appFinanceRouteRouteChildren,
)

interface appProfileRouteRouteChildren {
  appProfileIndexRoute: typeof appProfileIndexRoute
}

const appProfileRouteRouteChildren: appProfileRouteRouteChildren = {
  appProfileIndexRoute: appProfileIndexRoute,
}

const appProfileRouteRouteWithChildren = appProfileRouteRoute._addFileChildren(
  appProfileRouteRouteChildren,
)

interface appProgramsRouteRouteChildren {
  appProgramsCourseIdRoute: typeof appProgramsCourseIdRoute
  appProgramsIndexRoute: typeof appProgramsIndexRoute
}

const appProgramsRouteRouteChildren: appProgramsRouteRouteChildren = {
  appProgramsCourseIdRoute: appProgramsCourseIdRoute,
  appProgramsIndexRoute: appProgramsIndexRoute,
}

const appProgramsRouteRouteWithChildren =
  appProgramsRouteRoute._addFileChildren(appProgramsRouteRouteChildren)

interface appRouteRouteChildren {
  apphomeRouteRoute: typeof apphomeRouteRouteWithChildren
  appContactRouteRoute: typeof appContactRouteRouteWithChildren
  appFinanceRouteRoute: typeof appFinanceRouteRouteWithChildren
  appProfileRouteRoute: typeof appProfileRouteRouteWithChildren
  appProgramsRouteRoute: typeof appProgramsRouteRouteWithChildren
}

const appRouteRouteChildren: appRouteRouteChildren = {
  apphomeRouteRoute: apphomeRouteRouteWithChildren,
  appContactRouteRoute: appContactRouteRouteWithChildren,
  appFinanceRouteRoute: appFinanceRouteRouteWithChildren,
  appProfileRouteRoute: appProfileRouteRouteWithChildren,
  appProgramsRouteRoute: appProgramsRouteRouteWithChildren,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

interface authsigninRouteRouteChildren {
  authsigninSigninRoute: typeof authsigninSigninRoute
}

const authsigninRouteRouteChildren: authsigninRouteRouteChildren = {
  authsigninSigninRoute: authsigninSigninRoute,
}

const authsigninRouteRouteWithChildren = authsigninRouteRoute._addFileChildren(
  authsigninRouteRouteChildren,
)

interface authsignupRouteRouteChildren {
  authsignupSignupRoute: typeof authsignupSignupRoute
}

const authsignupRouteRouteChildren: authsignupRouteRouteChildren = {
  authsignupSignupRoute: authsignupSignupRoute,
}

const authsignupRouteRouteWithChildren = authsignupRouteRoute._addFileChildren(
  authsignupRouteRouteChildren,
)

interface authRouteRouteChildren {
  authsigninRouteRoute: typeof authsigninRouteRouteWithChildren
  authsignupRouteRoute: typeof authsignupRouteRouteWithChildren
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authsigninRouteRoute: authsigninRouteRouteWithChildren,
  authsignupRouteRoute: authsignupRouteRouteWithChildren,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  authRouteRoute: authRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
